<?php

use Drupal\Core\Entity\EntityTypeBundleInfoInterface;
use Drupal\entity_overview\Entity\Overview;

/**
 * Update Entity Overview with engine plugin support
 */
function entity_overview_update_9001() {
  $config_factory = \Drupal::configFactory();
  /** @var EntityTypeBundleInfoInterface $entityTypeBundleInfo */
  $entityTypeBundleInfo = \Drupal::service('entity_type.bundle.info');
  $list = $config_factory->listAll('entity_overview.');
  foreach ($list as $config_id) {
    $config = $config_factory->getEditable($config_id);
    if (!$config->isNew()) {
      $config->set('engine', 'entity_query');
      $config->set('show_total', '');
      $bundle_info = $entityTypeBundleInfo->getBundleInfo($config->get('entity_type_id'));
      $config->set('label', $bundle_info[$config->get('bundle')]['label']);
      $config->save();
    }
  }
}

/**
 * Update configurations to support multiple entity types
 */
function entity_overview_update_9004() {
  $config_factory = \Drupal::configFactory();
  $list = $config_factory->listAll('entity_overview.');
  foreach ($list as $config_id) {
    $old_config = $config_factory->getEditable($config_id);
    $id = str_replace('.', '_', $old_config->get('id'));
    if (!empty(Overview::load($id))) {
      continue;
    }
    /** @var \Drupal\entity_overview\Entity\Overview $new_config */
    $new_config = \Drupal\entity_overview\Entity\Overview::create([
      'id' => $id,
      'label' => $old_config->get('label')
    ]);
    $new_config->setEngineID($old_config->get('engine') ?? 'entity_query');
    if (empty($old_config->get('entity_bundles'))) {
      $entity_bundles = [
        $old_config->get('entity_type_id') => [$old_config->get('bundle')]
      ];
      $new_config->setEntityBundles($entity_bundles);
    } else {
      $new_config->setEntityBundles($old_config->get('entity_bundles') ?? []);
    }
    $new_config->setFields($old_config->get('fields') ?? []);
    $new_config->setSortField($old_config->get('sort_field') ?? []);
    $new_config->setShowTotal($old_config->get('show_total') ?? []);
    $new_config->save();
    $old_config->delete();
  }
}

/**
 * Install overview entity.
 */
function entity_overview_update_9005() {
  \Drupal::entityTypeManager()->clearCachedDefinitions();
  \Drupal::entityDefinitionUpdateManager()
    ->installEntityType(\Drupal::entityTypeManager()->getDefinition('entity_overview'));
}

/**
 * Uninstall html5history.
 */
function entity_overview_update_9006() {
  /** @var \Drupal\Core\Extension\ModuleInstaller $module_installer */
  $module_installer = \Drupal::service('module_installer');
  $module_installer->uninstall(['html5history']);
}
